version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - hg-net-dev
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    networks:
      - hg-net-dev
    volumes:
      - ./api:/usr/src/app
    ports:
      - "4000:4000"

networks:
  hg-net-dev:
