version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - hg-net-dev
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3001:3000"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    networks:
      - hg-net-dev
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "4001:4000"

networks:
  hg-net-dev:
