version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - hg-net
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - hg-net
    ports:
      - "4000:4000"

networks:
  hg-net:
